In [1]:
#from iex import reference
#reference.symbols()

#sandbox = https://sandbox.iexapis.com/
#production = https://cloud.iexapis.com

import requests
import pandas as pd
import numpy as np

secret_key = 'sk_ab9b552545f5434aa32147783847f0f7'
sandbox_key = 'Tsk_7e9daacab092400196ac13ad11ba9e2e'
publishable_key ='pk_d48a7ba0c84b4cd8a0725fe678d78b58'

#https://cloud.iexapis.com/stable/stock/IBM/chart?token=YOUR_TOKEN_HERE&period=annual
url = 'https://sandbox.iexapis.com/stable/stock/aapl/chart/5y?token=Tsk_7e9daacab092400196ac13ad11ba9e2e&period=annual&filter=date,open,close,high,low,volume'
#url = 'https://sandbox.iexapis.com/stable/stock/aapl/chart/5y?token=sk_ab9b552545f5434aa32147783847f0f7&period=annual&filter=date,open,close,high,low,volume'

def 


a= requests.get(url)

aa = a.json()

df = pd.DataFrame(aa)

df


date    open   close    high     low    volume
0     2015-06-10  134.31  131.17  134.07  134.16  39379849
1     2015-06-11  132.04  131.75  135.99  130.89  35600659
2     2015-06-12  129.19  127.21  129.30  128.68  37219768
3     2015-06-15  130.70  132.81  131.54  127.48  45120357
4     2015-06-16  128.75  127.70  133.81  129.26  32004530
...          ...     ...     ...     ...     ...       ...
1254  2020-06-03  329.51  340.11  341.20  327.70  26450443
1255  2020-06-04  334.88  336.94  339.48  333.45  22650367
1256  2020-06-05  332.61  347.20  346.89  323.28  34604579
1257  2020-06-08  334.69  347.15  336.20  335.79  24072649
1258  2020-06-09  342.94  351.02  362.03  333.28  37416507

[1259 rows x 6 columns]

In [2]:
#SMA

def SMA(close, periods):
    
    sma = np.zeros(periods - 1)
    count = 0

    
    for i in range(periods, len(close) + 1):
        periods_rng = list(range(count, i))
        smaC = close[periods_rng].sum() / periods
        sma = np.append(sma, smaC)
    
        count += 1

    return sma

print(SMA(df["close"], 9))



[  0.           0.           0.         ... 329.35333333 332.47333333
 335.89444444]


In [3]:
#function for ema calc
#fix function arguments


def ema(close, periods):

 
    sma = close[list(range(0,periods))].sum()/periods
    mult = 2/(periods + 1)

    ema_lst = np.zeros(periods-1)
    ema_lst = np.append(ema_lst,sma)


    for i in range(periods-1, close.size-1):
        ema = ((close[i] - ema_lst[i]) * mult) + ema_lst[i]
        ema_lst = np.append(ema_lst,ema)
  
    return ema_lst



df["ema"] = ema(df["close"],9)

df

date    open   close    high     low    volume         ema
0     2015-06-10  134.31  131.17  134.07  134.16  39379849    0.000000
1     2015-06-11  132.04  131.75  135.99  130.89  35600659    0.000000
2     2015-06-12  129.19  127.21  129.30  128.68  37219768    0.000000
3     2015-06-15  130.70  132.81  131.54  127.48  45120357    0.000000
4     2015-06-16  128.75  127.70  133.81  129.26  32004530    0.000000
...          ...     ...     ...     ...     ...       ...         ...
1254  2020-06-03  329.51  340.11  341.20  327.70  26450443  324.321251
1255  2020-06-04  334.88  336.94  339.48  333.45  22650367  327.479001
1256  2020-06-05  332.61  347.20  346.89  323.28  34604579  329.371201
1257  2020-06-08  334.69  347.15  336.20  335.79  24072649  332.936961
1258  2020-06-09  342.94  351.02  362.03  333.28  37416507  335.779569

[1259 rows x 7 columns]

In [15]:
#TR 

def TR(high, low, close, periods):
    
    trmeth = np.zeros(3)
    tRng = np.empty(0)

    #make array of TR
    for i in range(0, len(high)):
        #Method 1
        trmeth[0] = high[i] - low[i]
        #Method 2 & 3
        if i-1 >= 0:
            trmeth[1] = abs(high[i] - close[i-1])
            
            trmeth[2] = abs(low[i] - close[i-1])
        else:
            trmeth[1] = 0
            
            trmeth[2] = 0 
            
        trng = np.append(trng,np.amax(TRmeth))
            
            
    return trng

    

In [20]:
# ATR

#TR take greatest of the methods below
# Method 1: Current High less the current Low
# Method 2: Current High less the previous Close (absolute value)
# Method 3: Current Low less the previous Close (absolute value)

def ATR(high, low, close, periods):

    trng = TR(high, low, close, periods)

    #array for ATR
    atrng = np.zeros(periods-1)
    atrng = np.append(atrng,np.average(trng[0:periods]))

    prev_per = 0

    for i in range(periods, len(high)):
        prev_atrng = atrng[-1]
        current_atrng = ((prev_atrng * 13) + trng[i]) / periods
        atrng = np.append(atrng, current_atrng)
        
    return (trng, atrng)

atr = ATR(df["high"], df["low"], df["close"], 14)
df["TR"]  = atr[0]
df["ATR"] = atr[1]
df

date    open   close    high     low    volume         ema     TR  \
0     2015-06-10  134.31  131.17  134.07  134.16  39379849    0.000000   0.00   
1     2015-06-11  132.04  131.75  135.99  130.89  35600659    0.000000   5.10   
2     2015-06-12  129.19  127.21  129.30  128.68  37219768    0.000000   3.07   
3     2015-06-15  130.70  132.81  131.54  127.48  45120357    0.000000   4.33   
4     2015-06-16  128.75  127.70  133.81  129.26  32004530    0.000000   4.55   
...          ...     ...     ...     ...     ...       ...         ...    ...   
1254  2020-06-03  329.51  340.11  341.20  327.70  26450443  324.321251  13.99   
1255  2020-06-04  334.88  336.94  339.48  333.45  22650367  327.479001   6.66   
1256  2020-06-05  332.61  347.20  346.89  323.28  34604579  329.371201  23.61   
1257  2020-06-08  334.69  347.15  336.20  335.79  24072649  332.936961  11.41   
1258  2020-06-09  342.94  351.02  362.03  333.28  37416507  335.779569  28.75   

            ATR       KeltL       KeltM       KeltU  
0      0.000000    0.000000    0.000000    0.000000  
1      0.000000    0.000000    0.000000    0.000000  
2      0.000000    0.000000    0.000000    0.000000  
3      0.000000    0.000000    0.000000    0.000000  
4      0.000000    0.000000    0.000000    0.000000  
...         ...         ...         ...         ...  
1254  10.632173  314.886314  317.895153  320.903992  
1255  10.348446  317.389107  320.010853  322.632598  
1256  11.295700  317.558018  321.623152  325.688287  
1257  11.303864  320.275705  324.059043  327.842380  
1258  12.550017  320.924012  326.258181  331.592351  

[1259 rows x 12 columns]

In [5]:
#Keltner Channels

def Keltner(ema, atr, periods):
    kelt = np.zeros(3)
    keltL = np.empty(0)
    keltM = np.empty(0)
    keltU = np.empty(0)
    
    for i in range(0,len(ema)):
        kelt[0] = ema[i] - (2 * atr[i])
        kelt[1] = ema[i] 
        kelt[2] = ema[i] + (2 * atr[i])
        
        #keltall.append(kelt)
        keltU = np.append(keltU, kelt[0])
        keltM = np.append(keltM, kelt[1])
        keltL = np.append(keltL, kelt[2])
        
    return (keltU, keltM, keltL)
# print(ema(df["close"],20))  

kelt = Keltner(ema(df["close"],20),ATR(df["high"], df["low"], df["close"], 20)[1], 20)
df["KeltL"]= kelt[0]
df["KeltM"]= kelt[1]
df["KeltU"]= kelt[2]
df



date    open   close    high     low    volume         ema     TR  \
0     2015-06-10  134.31  131.17  134.07  134.16  39379849    0.000000   0.00   
1     2015-06-11  132.04  131.75  135.99  130.89  35600659    0.000000   5.10   
2     2015-06-12  129.19  127.21  129.30  128.68  37219768    0.000000   3.07   
3     2015-06-15  130.70  132.81  131.54  127.48  45120357    0.000000   4.33   
4     2015-06-16  128.75  127.70  133.81  129.26  32004530    0.000000   4.55   
...          ...     ...     ...     ...     ...       ...         ...    ...   
1254  2020-06-03  329.51  340.11  341.20  327.70  26450443  324.321251  13.99   
1255  2020-06-04  334.88  336.94  339.48  333.45  22650367  327.479001   6.66   
1256  2020-06-05  332.61  347.20  346.89  323.28  34604579  329.371201  23.61   
1257  2020-06-08  334.69  347.15  336.20  335.79  24072649  332.936961  11.41   
1258  2020-06-09  342.94  351.02  362.03  333.28  37416507  335.779569  28.75   

            ATR       KeltL       KeltM       KeltU  
0      0.000000    0.000000    0.000000    0.000000  
1      0.000000    0.000000    0.000000    0.000000  
2      0.000000    0.000000    0.000000    0.000000  
3      0.000000    0.000000    0.000000    0.000000  
4      0.000000    0.000000    0.000000    0.000000  
...         ...         ...         ...         ...  
1254  10.632173  314.886314  317.895153  320.903992  
1255  10.348446  317.389107  320.010853  322.632598  
1256  11.295700  317.558018  321.623152  325.688287  
1257  11.303864  320.275705  324.059043  327.842380  
1258  12.550017  320.924012  326.258181  331.592351  

[1259 rows x 12 columns]

In [6]:
# RSI


def RSI(close,periods):
    #Gain & Loss
    gain = np.zeros(1)
    loss = np.zeros(1)
    
    for i in range(1, len(close)):
        change = close[i] - close[i - 1]
        
        if change > 0:
            gain = np.append(gain, change)
            loss = np.append(loss, 0)
            
        elif change < 0:
            gain = np.append(gain, 0)
            loss = np.append(loss, abs(change))
            
        else:
            gain = np.append(gain, 0)
            loss = np.append(loss, 0)

            
    #Avg Gain & Avg Loss
    avgG = np.append(np.zeros(periods - 1), np.average(gain[0:periods]))
    avgL = np.append(np.zeros(periods - 1), np.average(loss[0:periods]))
    rsi = np.append(np.zeros(periods - 1), 100 - (100 / (1 + (np.average(gain[0:periods] / np.average(loss[0:periods]))))))

    
    for i in range(periods, len(close)):
        avgG = np.append(avgG, ((avgG[i - 1] * 13) + gain[i]) / 14)
        avgL = np.append(avgL, ((avgL[i - 1] * 13) + loss[i]) / 14)
        rsi = np.append(rsi, 100 - (100 / (1 + (avgG[i] / avgL[i]))))\
        
    return rsi
 
print(RSI(df["close"], 14))
    
    
    
    

[ 0.          0.          0.         ... 67.15620499 67.11504343
 68.71345604]


In [7]:
#Bollinger Bands
from math import sqrt

"""
  * Middle Band = 20-day simple moving average (SMA)
  * Upper Band = 20-day SMA + (20-day standard deviation of price x 2) 
  * Lower Band = 20-day SMA - (20-day standard deviation of price x 2)
"""

def Bollinger(close, periods):
    
    sd = np.zeros(periods - 1)
    
    bolL = np.zeros(periods - 1)
    bolM = SMA(df["close"] , periods)
    bolU = np.zeros(periods - 1)
    
    per_range = list(range(0,periods))
    count = 0
    
    for i in range(periods, len(close)+1):
        sd_per = close[list(range(count, i))]
        sd_per = (sd_per - bolM[i - 1]) ** 2
        sd_per = sqrt(np.average(sd_per))

        sd = np.append(sd, sd_per)

        count += 1
        
        bolL = np.append(bolL, bolM[i-1] - (2 * sd[i-1]))
        bolU = np.append(bolU, bolM[i-1] + (2 * sd[i-1]))
        
    
    
    return (bolL, bolM, bolU)
    
    
Bollinger(df["close"], 20)

        
        
    
        

(array([  0.        ,   0.        ,   0.        , ..., 307.35632035,
        306.60480496, 305.83031987]),
 array([  0.    ,   0.    ,   0.    , ..., 324.957 , 326.3925, 327.9975]),
 array([  0.        ,   0.        ,   0.        , ..., 342.55767965,
        346.18019504, 350.16468013]))

In [26]:
#ADX

def ADX(high, low, close, periods):
  
    trng = TR(high, low, close, periods)
    

    #directional movement
    dmP = np.zeros(1)
    dmN = np.zeros(1)
    
    for i in range(1, len(high)):
        
        dmPC = high[i] - high[i-1] 
        dmP = np.append(dmP, dmPC)
        dmNC = low[i-1] - low[i]
        dmN = np.append(dmN, dmNC)
        
    #smoothed directional movement    
    sm_dmP = np.append(np.zeros(periods), np.sum(dmP[0:periods]))
    sm_dmN = np.append(np.zeros(periods), np.sum(dmN[0:periods]))
    
    print(sm_dmP)
    print(sm_dmN)

#     for i in range(periods, len(high)):
        
#         per_rng = list(range())
        
ADX( df["high"], df["low"], df["close"], 20)
        
        

[ 0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.    0.
  0.    0.    0.    0.    0.    0.    0.    0.   -7.23]
[0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.   0.
 0.   0.   0.   0.   0.   0.   6.88]
